# FONTS
ENTRY_FONT = ("Times New Roman", 19, "normal")
TIMER_FONT = ("Lucida Sans Typewriter", 160, "bold")
TIMER_LABEL_FONT = ("Roboto Slab", 25, "normal")
WORD_COUNT_FONT = ("Lucida Sans Typewriter", 100, "bold")
WORD_COUNT_LABEL_FONT = TIMER_LABEL_FONT
TIPS_FONT = ("Times New Roman", 15, "normal")
CANVAS_TIP_FONT = ("Times New Roman", 30, "normal")
BOTTOM_FONT = TIPS_FONT
LOGO_FONT = ("Roboto Slab", 40, "bold")
START_FONT = TIMER_LABEL_FONT

# COLORS
BG_COLOR = "#0A3D51"
FRAME_COLOR = "#259DD8"
TYPE_TEXT_COLOR = "#FFFFFF"
ENTRY_TEXT_COLOR = TYPE_TEXT_COLOR
SCROLL_COLOR = "#000000"
EDIT_COLOR = BG_COLOR
TIMER_COLOR = FRAME_COLOR
WORD_COUNT_COLOR = TIMER_COLOR
BOTTOM_TEXT_COLOR = TIMER_COLOR
START_BTN_COLOR = SCROLL_COLOR
MENU_BTN_COLOR = "#0980AF"
MENU_HOVER_COLOR = "#09698E"
STARTED_BG_COLOR = "#890906"
TIME_COUNT_COLOR = "#06602C"
RESTART_HOVER_COLOR = "#02913F"
TIPS_COLOR = SCROLL_COLOR
